name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
        
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build APK
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug --stacktrace
        
    - name: List build outputs (برای دیباگ)
      run: find app/build/outputs -name "*.apk"
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: |
          app/build/outputs/apk/debug/*.apk
          app/build/outputs/apk/release/*.apk
        if-no-files-found: error
        retention-days: 5
